### ISSUE TITLE
Failed to install on Fedora 24 due to strdup error in mtex2MML

### ISSUE THREAD

**Issue by ProgramFan** [gjtorikian/mathematical#64]
`gem install mathematical-1.6.7` fails on Fedora 24 (with gcc 6.1) with the following error:

```
current directory: /home/zyang/.local/share/rvm/gems/ruby-2.3.0/gems/mathematical-1.6.7/ext/mathematical
make "DESTDIR="
compiling lasem_overrides.c
In file included from /usr/include/string.h:630:0,
                 from /home/zyang/.local/share/rvm/gems/ruby-2.3.0/gems/mathematical-1.6.7/ext/mathematical/mtex2MML/src/../deps/uthash/uthash.h:29,
                 from /home/zyang/.local/share/rvm/gems/ruby-2.3.0/gems/mathematical-1.6.7/ext/mathematical/mtex2MML/src/environment.h:4,
                 from /home/zyang/.local/share/rvm/gems/ruby-2.3.0/gems/mathematical-1.6.7/ext/mathematical/mtex2MML/src/mtex2MML.h:12,
                 from lasem_overrides.c:5:
/home/zyang/.local/share/rvm/gems/ruby-2.3.0/gems/mathematical-1.6.7/ext/mathematical/mtex2MML/src/../deps/uthash/../strdup/strdup.h:24:1: error: expected identifier or ‘(’ before ‘__extension__’
 strdup(const char *str);
 ^
lasem_overrides.c: In function ‘lsm_itex_to_mathml’:
lasem_overrides.c:23:1: warning: control reaches end of non-void function [-Wreturn-type]
 lsm_itex_to_mathml (const char *itex, gssize size) { }
 ^~~~~~~~~~~~~~~~~~
Makefile:238: recipe for target 'lasem_overrides.o' failed
make: *** [lasem_overrides.o] Error 1
```

**Comment by ProgramFan** [comment]
It seems the `strdup` override conflict with the real `strdup` in `string.h`. Commenting out the strdup declaration in `mtex2MML/deps/strdup/strdup.h` solves the problem.

**Comment by gjtorikian** [comment]
Could you try installing with the environment variable `MATHEMATICAL_SKIP_STRDUP` enabled, such as:

```
MATHEMATICAL_SKIP_STRDUP=1 gem install mathematical
```

This problem has begun recently and I confess I don't know what is causing it. I thought that the `ifdef` in mtex2mml would take care of conflicts with strdup but that does not seem to be the case. strdup is not part of the C standard so I felt the need to include it. Perhaps I ought to rename the file (`string_dupe`?) so that it does not conflict with existing implementations? Do you have any suggestions?

**Comment by ProgramFan** [comment]
`MATHEMATICAL_SKIP_STRDUP=1` solves the problem perfectly. I have tried to comment out the strdup line and it broke mtex2MML compilation (although the aforementioned file compiled). The CMakeLists.txt of mtex2MML also lacks proper support to detect `HAVE_STRDUP` properly. If `strdup` is only used internally by mtex2MML, I would suggest rename it.

**Comment by gjtorikian** [comment]
> The CMakeLists.txt of mtex2MML also lacks proper support to detect HAVE_STRDUP

I'm not sure what you mean by this but if you know of a fix, I would very much appreciate a pull request! https://github.com/gjtorikian/mtex2MML

I'll close this out for now since the original issue is solved and, pending an update to the CMakeLists file, I may just rename method to avoid conflict.

**Comment by akosma** [comment]
This fix does not work in macOS Mojave 10.14, and the gem cannot be installed.

**Comment by aronayne** [comment]
Can also confirm this fix does not work in macOS Mojave 10.14.

**Comment by mocenigo** [comment]
Well, we are now at Tahoe and still cannot get this to work

**Comment by gjtorikian** [comment]
mathematical ships fat binaries that are precompiled for different architectures: https://rubygems.org/gems/mathematical/versions/1.7.0-arm64-darwin

what exactly is not working? building from source? I'm on macOS and can build it.

**Comment by mocenigo** [comment]
> mathematical ships fat binaries that are precompiled for different architectures: https://rubygems.org/gems/mathematical/versions/1.7.0-arm64-darwin
> 
> what exactly is not working? building from source? I'm on macOS and can build it.

Actually, I am not 100% sure about what does not work.
I install mathematical
```
gem install mathematical
```
then I cannot install asciidoctor-mathematical with `gem install asciidoctor-mathematical`, so I modify the gemfile for more recent dependencies, and install it (0.3.6) from source. But then, when I compile something with asciidoctor, I get it cannot find "mathematical/mathematical":

23:47:07 asciidoctor-mathematical  (git)-[master]- » asciidoctor-pdf -r asciidoctor-mathematical -o test.pdf sample.adoc
**cannot load such file -- mathematical/mathematical**

and here I am simply stumped.


Edit: If I add the --trace option I get

```
23:50:01 asciidoctor-mathematical  (git)-[master]- » asciidoctor-pdf -r asciidoctor-mathematical -o test.pdf sample.adoc --trace
/opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require': cannot load such file -- mathematical/mathematical (LoadError)
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/mathematical-1.7.0-arm64-darwin/lib/mathematical.rb:9:in '<top (required)>'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-mathematical-0.3.6/lib/asciidoctor-mathematical/extension.rb:27:in 'MathematicalTreeprocessor#process'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:545:in 'Method#[]'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:545:in 'block in Asciidoctor::Document#parse'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:544:in 'Array#each'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:544:in 'Asciidoctor::Document#parse'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/load.rb:84:in 'Asciidoctor.load'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:78:in 'Asciidoctor.convert'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:190:in 'block in Asciidoctor.convert_file'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:190:in 'IO.open'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:190:in 'Asciidoctor.convert_file'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/cli/invoker.rb:129:in 'block in Asciidoctor::Cli::Invoker#invoke!'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/cli/invoker.rb:112:in 'Array#each'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/cli/invoker.rb:112:in 'Asciidoctor::Cli::Invoker#invoke!'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-pdf-2.3.24/bin/asciidoctor-pdf:46:in '<top (required)>'
	from /opt/homebrew/Cellar/ruby/4.0.5/lib/ruby/4.0.0/rubygems.rb:305:in 'Kernel#load'
	from /opt/homebrew/Cellar/ruby/4.0.5/lib/ruby/4.0.0/rubygems.rb:305:in 'Gem.activate_and_load_bin_path'
	from /opt/homebrew/lib/ruby/gems/4.0.0/bin/asciidoctor-pdf:25:in '<main>'
/opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require': dlopen(/opt/homebrew/lib/ruby/gems/4.0.0/gems/mathematical-1.7.0-arm64-darwin/lib/mathematical/4.0/mathematical.bundle, 0x0009): Library not loaded: /Users/runner/hostedtoolcache/Ruby/4.0.2/arm64/lib/libruby.4.0.dylib (LoadError)
  Referenced from: <AB87EAAB-20F2-3E8D-8299-78B215D7D781> /opt/homebrew/lib/ruby/gems/4.0.0/gems/mathematical-1.7.0-arm64-darwin/lib/mathematical/4.0/mathematical.bundle
  Reason: tried: '/Users/runner/hostedtoolcache/Ruby/4.0.2/arm64/lib/libruby.4.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/hostedtoolcache/Ruby/4.0.2/arm64/lib/libruby.4.0.dylib' (no such file), '/Users/runner/hostedtoolcache/Ruby/4.0.2/arm64/lib/libruby.4.0.dylib' (no such file) - /opt/homebrew/lib/ruby/gems/4.0.0/gems/mathematical-1.7.0-arm64-darwin/lib/mathematical/4.0/mathematical.bundle
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/mathematical-1.7.0-arm64-darwin/lib/mathematical.rb:7:in '<top (required)>'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in 'Kernel#require'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-mathematical-0.3.6/lib/asciidoctor-mathematical/extension.rb:27:in 'MathematicalTreeprocessor#process'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:545:in 'Method#[]'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:545:in 'block in Asciidoctor::Document#parse'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:544:in 'Array#each'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/document.rb:544:in 'Asciidoctor::Document#parse'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/load.rb:84:in 'Asciidoctor.load'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:78:in 'Asciidoctor.convert'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:190:in 'block in Asciidoctor.convert_file'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:190:in 'IO.open'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/convert.rb:190:in 'Asciidoctor.convert_file'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/cli/invoker.rb:129:in 'block in Asciidoctor::Cli::Invoker#invoke!'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/cli/invoker.rb:112:in 'Array#each'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-2.0.26/lib/asciidoctor/cli/invoker.rb:112:in 'Asciidoctor::Cli::Invoker#invoke!'
	from /opt/homebrew/lib/ruby/gems/4.0.0/gems/asciidoctor-pdf-2.3.24/bin/asciidoctor-pdf:46:in '<top (required)>'
	from /opt/homebrew/Cellar/ruby/4.0.5/lib/ruby/4.0.0/rubygems.rb:305:in 'Kernel#load'
	from /opt/homebrew/Cellar/ruby/4.0.5/lib/ruby/4.0.0/rubygems.rb:305:in 'Gem.activate_and_load_bin_path'
	from /opt/homebrew/lib/ruby/gems/4.0.0/bin/asciidoctor-pdf:25:in '<main>'
```

**Comment by mocenigo** [comment]
Note that `'/Users/runner/hostedtoolcache/Ruby/4.0.2/arm64/lib/libruby.4.0.dylib' does not exist on my machine, since there is no user called "runner"
